### PR TITLE
Revert document store createOrReplace api

### PR DESCRIPTION
**Pull request by bhubam**
## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 

### Checklist:
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### Documentation
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.

### CODE REVIEW

**Comment by bhubam** [comment]
https://github.com/hypertrace/config-service/pull/255/files?file-filters%5B%5D=.java&show-viewed-files=true#r1851946346, we have a usecase were value starts with `$` (ex: were we provide jsonpath as input, it starts with `$`)

**Comment by harshit-kumar-v2** [comment]
> https://github.com/hypertrace/config-service/pull/255/files?file-filters%5B%5D=.java&show-viewed-files=true#r1851946346, we have a usecase were value starts with `$` (ex: were we provide jsonpath as input, it starts with `$`) cc @suresh-prakash @harshit-kumar-v2

This is issue with this new api, please file a bug with the log.

**Review by harshit-kumar-v2 — DISMISSED** [review]

**Review by avinashkolluru — DISMISSED** [review]

**Comment by aaron-steinfeld** [comment]
Overriding dep check for this PR as NVD is currently unavailable.

**Comment by aaron-steinfeld** [comment]
(oops forgot to approve - approved :) )

**Pull request merged**
